[build]
builder = "nixpacks"
buildCommand = "npm run staging:build && npm run staging:db:clean"

[deploy]
startCommand = "npm run staging:db:seed && npm run staging:start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.env]
APP_ENV = "staging" 
NODE_ENV = "production"